spring:
  application:
    name: backend
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
  cache:
    type: simple
springdoc:
  swagger-ui:
    path: /swagger-ui.html
